name: lilURL-Test

services:
  frontend-build:
    build:
      context: ./Frontend
      dockerfile: frontend.build.Dockerfile
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - lilUrl-Frontend-Build:/app/build
    container_name: lilUrl_frontend_test
    env_file:
      - $FRONTEND_ENV
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    env_file:
      - $BACKEND_ENV
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - lilUrl-Frontend-Build:/app/Frontend
    container_name: lilUrl_backend_test
    depends_on:
      - lilURL_DB
      - lilURL_redis

  lilURL_redis:
    image: redis:8.2-alpine
    container_name: lilURL_redis_test
    ports:
      - $REDIS_PORT:6379
    volumes:
      - lilURL-redis-data-test:/data
    restart: unless-stopped

  lilURL_DB:
    image: postgres:15-alpine
    container_name: lilURL_DB_test
    restart: unless-stopped
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - pgData-lilURL-test:/var/lib/postgresql/data

volumes:
  lilURL-redis-data-test:
  pgData-lilURL-test:
  lilUrl-Frontend-Build: