name: lilURL-Test

services:
  frontend-build:
    build:
      context: ./Frontend
      dockerfile: frontend.build.Dockerfile
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - lilUrl-Frontend-Build:/app/build
    container_name: lilUrl_frontend_test
    env_file:
      - $FRONTEND_ENV
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: backend.Dockerfile
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    env_file:
      - $BACKEND_ENV
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - lilUrl-Frontend-Build:/app/Frontend
    container_name: lilUrl_backend_test
    depends_on:
      lilURL_DB:
        condition: service_healthy
      lilURL_redis:
        condition: service_healthy
      lilURL_Read:
        condition: service_healthy

  lilURL_redis:
    image: redis:8.2-alpine
    container_name: lilURL_redis_test
    ports:
      - $REDIS_PORT:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  lilURL_DB:
    image: postgres:15-alpine
    container_name: lilURL_DB_Test_Write
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    command: >
      postgres -c wal_level=replica
               -c max_wal_senders=10
               -c max_replication_slots=10
               -c listen_addresses='*'
    volumes:
      - ./init-repl.sh:/docker-entrypoint-initdb.d/init-repl.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  lilURL_Read:
    image: postgres:15-alpine
    container_name: lilURL_DB_Test_Read
    restart: unless-stopped
    expose:
      - 5432
    environment:
      PGPASSWORD: replpass
    command: >
      bash -c "
        sleep 15 &&
        rm -rf /var/lib/postgresql/data/* &&
        su-exec postgres pg_basebackup -h lilURL_DB_Test_Write -U repl -D /var/lib/postgresql/data -Fp -Xs -P -R &&
        chown -R postgres:postgres /var/lib/postgresql/data &&
        chmod 700 /var/lib/postgresql/data &&
        exec su-exec postgres postgres
      "
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      lilURL_DB:
        condition: service_healthy

volumes:
  lilUrl-Frontend-Build: