export {redirectRouter} from './redirect/routes/redirectRoute.js'
export {authRouter} from './auth/routes/authRoute.js'
export {analyticsRouter} from './analytics/routes/analyticsRoute.js'
export {updateRouter} from './update/routes/updateRouter.js'
export {getRouter} from './get/routes/getRouter.js'